In [1]:
import numpy as np
import pandas as pd

fpath = 'input.txt'
# fpath = 'test.txt'
# fpath = 'test2.txt'

# Part 1!

# def solve(days, state): 
#     # fish_0 = 0
#     for day in range(1, days+1):
#         # Process current fish
#         adult_fish = len(state)
#         for idx in range(adult_fish):
#             if state[idx] == 0:
#                 state[idx] = 6
#                 state.append(8)
#             else:
#                 state[idx] -= 1
#         # print(f"{day=}, {state=}")

#     return days, len(state), state


# with open(fpath, 'r') as ifp:
#     state = list(map(int, ifp.readline().strip().split(',')))

# upper_bound = 80
# prev_value = 0
# result = []
# for days in range(1, upper_bound+1):
#     state = [8]
#     day_count, fish_count, fish = solve(days, state)
#     day_word = "days" if days != 1 else "day"
#     fish_verb = "is" if fish_count == 1 else "are"
#     print(f"After '{day_count}' {day_word} there {fish_verb} '{fish_count}' fish. (diff = {fish_count-prev_value})")
#     prev_value = fish_count
#     result.append(fish_count)
# result = np.array(result)
# np.savetxt("list.csv", result.astype(int), fmt='%i', delimiter=",")

In [2]:
# Base solver
def solve(days, state): 
    for day in range(1, days+1):
        # Process current fish
        adult_fish = len(state)
        for idx in range(adult_fish):
            if state[idx] == 0:
                state[idx] = 6
                state.append(8)
            else:
                state[idx] -= 1

    return days, adult_fish, state

In [3]:
# Part 2!
days = 256

# Initalize known values
m = np.zeros(shape=(days+2, 9))
m = pd.DataFrame(m)
m.index.name = 'day'
for day in range(1,9):
    for age in m.columns:
        _, fish_count, _ = solve(day, [age])
        m.iloc[day, age] = fish_count

m.iloc[0, 0:8] = 1
m.iloc[0:2,0] = 2

# Dynamically solve the remaining values
for day in range(9, days + 2):
    # For each of the actual 8 ages to consider, calculate the value
    for age in range(0, 8):
        # print(f"{day=}, {age=}")
        m.iloc[day, age] = m.iloc[day-7, age] + m.iloc[day-8, age+1]
    # Literal edge case, the 8th age
    m.iloc[day, 8] = m.iloc[day-1, 7]
m.to_csv("result.csv")
m

,0,1,2,3,4,5,6,7,8
day,,,,,,,,,
0,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00
1,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
2,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
3,2.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
4,2.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
...,...,...,...,...,...,...,...,...,...
253,4.726101e+09,4.368232e+09,3.989468e+09,3.649886e+09,3.369187e+09,3.053202e+09,2.837634e+09,2.563888e+09,2.379589e+09
254,5.217223e+09,4.726101e+09,4.368232e+09,3.989468e+09,3.649886e+09,3.369187e+09,3.053202e+09,2.837634e+09,2.563888e+09
255,5.617089e+09,5.217223e+09,4.726101e+09,4.368232e+09,3.989468e+09,3.649886e+09,3.369187e+09,3.053202e+09,2.837634e+09
256,6.206821e+09,5.617089e+09,5.217223e+09,4.726101e+09,4.368232e+09,3.989468e+09,3.649886e+09,3.369187e+09,3.053202e+09
257,6.703087e+09,6.206821e+09,5.617089e+09,5.217223e+09,4.726101e+09,4.368232e+09,3.989468e+09,3.649886e+09,3.369187e+09

In [4]:
with open(fpath, 'r') as ifp:
    ages = list(map(int, ifp.readline().strip().split(',')))
ages

total = 0
day_of_interest = days + 1
for age in ages:
   total += m.iloc[day_of_interest, age]
total

# I want 5934 (80 days) or 26 (18 days)

1749945484935.0